/** @type {import('next').NextConfig} */
const privateNoStoreHeaders = [
  { key: 'Cache-Control', value: 'private, no-store, max-age=0, must-revalidate' },
  { key: 'CDN-Cache-Control', value: 'private, no-store' },
  { key: 'Cloudflare-CDN-Cache-Control', value: 'private, no-store' },
];

const nextConfig = {
  poweredByHeader: false,
  trailingSlash: false,

  async headers() {
    return [
      {
        source: '/checkout',
        headers: privateNoStoreHeaders,
      },
      {
        source: '/account',
        headers: privateNoStoreHeaders,
      },
      {
        source: '/account/orders',
        headers: privateNoStoreHeaders,
      },
      {
        source: '/order-success',
        headers: privateNoStoreHeaders,
      },
      {
        source: '/track-order',
        headers: privateNoStoreHeaders,
      },
      {
        source: '/wishlist',
        headers: privateNoStoreHeaders,
      },
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options',             value: 'DENY' },
          { key: 'X-Content-Type-Options',       value: 'nosniff' },
          { key: 'Referrer-Policy',              value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy',           value: 'camera=(), microphone=(), geolocation=()' },
          { key: 'Strict-Transport-Security',    value: 'max-age=15552000; includeSubDomains; preload' },
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://connect.facebook.net https://*.cloudflare.com https://static.cloudflareinsights.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "img-src 'self' data: blob: https://e-mart.com.bd https://*.e-mart.com.bd https://*.woocommerce.com https://www.facebook.com https://connect.facebook.net https://www.google.com https://*.google.com https://*.google.com.bd https://www.google-analytics.com https://www.googletagmanager.com https://img.youtube.com https://*.tiktokcdn.com https://*.tiktokcdn-eu.com https://*.tiktokcdn-us.com",
              "font-src 'self' data: https://fonts.gstatic.com",
              "connect-src 'self' https://e-mart.com.bd wss://e-mart.com.bd https://www.tiktok.com https://www.google-analytics.com https://analytics.google.com https://region1.google-analytics.com https://www.google.com https://*.google.com https://*.google.com.bd https://*.doubleclick.net https://*.facebook.com https://connect.facebook.net https://www.googletagmanager.com https://cloudflareinsights.com",
              "frame-src 'self' https://www.facebook.com",
              "frame-ancestors 'none'",
              "base-uri 'self'",
              "form-action 'self' https://www.facebook.com",
            ].join('; '),
          },
        ],
      },
    ];
  },

  async redirects() {
    return [
      // /origins?country=X → /origins/X (301 — old query-param URLs to clean paths)
      { source: '/origins', has: [{ type: 'query', key: 'country', value: '(?<c>.+)' }], destination: '/origins/:c', permanent: true },
      { source: '/category/skincare',       destination: '/category/skincare-essentials', permanent: true },
      { source: '/category/skin-care',      destination: '/category/skincare-essentials', permanent: true },
      { source: '/product-category/skincare', destination: '/category/skincare-essentials', permanent: true },
      { source: '/product-category/skin-care/:path*', destination: '/category/skincare-essentials', permanent: true },
      // P2 404 cleanup batch 1 — high-confidence stale URL aliases
      { source: '/shop/kaine_kombu-hydrating-daily-cleanser-155g', destination: '/shop/kaine-kombu-hydrating-daily-cleanser-155g', permanent: true },
      { source: '/shop/dr-ceuracle-5%CE%B1-control-no-sebum-sun-lotion-spf50-pa-50g', destination: '/shop/dr-ceuracle-5alpha-control-no-sebum-sun-lotion-spf50-pa-50g', permanent: true },
      { source: '/shop/b_lab-matcha-hydrating-real-sun-stick-21g', destination: '/shop/b-lab-matcha-hydrating-real-sun-stick-21g', permanent: true },
      { source: '/shop/round-lab-eng-1025-dokdo-ampule_45g', destination: '/shop/round-lab-eng-1025-dokdo-ampule-45g', permanent: true },
      { source: '/brands/a-pieu', destination: '/brands/apieu', permanent: true },
      { source: "/brands/i'm-from", destination: '/brands/i-am-from', permanent: true },
      { source: '/brands/i-m-from', destination: '/brands/i-am-from', permanent: true },
      { source: '/brands/aztec', destination: '/brands/aztec-secret', permanent: true },
      { source: '/brands/paula-s', destination: '/brands/paulas-choice', permanent: true },
      { source: '/brands/wskin', destination: '/brands/wskinlab', permanent: true },
      { source: '/brands/purito', destination: '/brands/purito-seoul', permanent: true },
      { source: '/brands/lucido', destination: '/brands/lucido-l', permanent: true },
      { source: '/brands/tresemm', destination: '/brands/tresemme', permanent: true },
      { source: '/brands/absolute', destination: '/brands/absolute-new-york', permanent: true },
      { source: '/brands/bath', destination: '/brands/bath-and-body-works', permanent: true },
      { source: '/brands/house', destination: '/brands/house-of-hur', permanent: true },
      { source: '/brands/valencia', destination: '/brands/valencia-gio', permanent: true },
      { source: '/category/skincare/melasma', destination: '/category/melasma', permanent: true },
      { source: '/category/skincare/acne', destination: '/category/acne-blemish-care', permanent: true },
      { source: '/category/skincare/j-beauty-skincare', destination: '/category/japanese-beauty', permanent: true },
      { source: '/category/skincare/korean-skincare-routine', destination: '/category/korean-beauty', permanent: true },
      { source: '/product-category/skincare/j-beauty-skincare', destination: '/category/japanese-beauty', permanent: true },
      { source: '/product-category/skincare/korean-skincare-routine', destination: '/category/korean-beauty', permanent: true },
      { source: '/about-us-3', destination: '/about-us', permanent: true },
      { source: '/category/hair-personal-care/bath-body', destination: '/category/bath-body', permanent: true },
      { source: '/category/hair-care/hair-oil', destination: '/category/hair-oil', permanent: true },
      { source: '/category/health-wellbeing/general-health', destination: '/category/general-health', permanent: true },
      { source: '/product-category/hair-personal-care/bath-body', destination: '/category/bath-body', permanent: true },
      { source: '/product-category/hair-care/hair-oil', destination: '/category/hair-oil', permanent: true },
      { source: '/product-category/health-wellbeing/general-health', destination: '/category/general-health', permanent: true },
      { source: '/faq-FAQ', destination: '/faq', permanent: true },
      { source: '/home', destination: '/', permanent: true },
      { source: '/product-category/:slug*', destination: '/category/:slug*', permanent: true },
      { source: '/product/:slug',           destination: '/shop/:slug',      permanent: true },
      { source: '/shop/cosrx-advanced-snail-96-mucin-power-essence-30ml-mini', destination: '/shop/cosrx-advanced-snail-mucin-96-power-essence-30ml', permanent: true },
      { source: '/brands/april-skin',       destination: '/brands/aprilskin', permanent: true },
      { source: '/product-tag/:slug*',      destination: '/shop',            permanent: true },
      { source: '/tag/:slug*',              destination: '/shop',            permanent: true },
      { source: '/my-account',              destination: '/account',         permanent: true },
      { source: '/my-account/',             destination: '/account',         permanent: true },
      { source: '/my-account/:path*',       destination: '/account',         permanent: true },
      { source: '/cart',                    destination: '/checkout',        permanent: false },
      { source: '/contact-us',             destination: '/contact',          permanent: true },
      { source: '/contact-us/',            destination: '/contact',          permanent: true },
      { source: '/order-tracking',         destination: '/track-order',      permanent: true },
      { source: '/order-tracking/',        destination: '/track-order',      permanent: true },
      { source: '/homepage',               destination: '/',                 permanent: true },
      { source: '/homepage/',              destination: '/',                 permanent: true },
      { source: '/shop/%e0%a6%a6%e0%a6%be%e0%a6%97-%e0%a6%aa%e0%a6%bf%e0%a6%97%e0%a6%ae%e0%a7%87%e0%a6%a8%e0%a7%8d%e0%a6%9f%e0%a7%87%e0%a6%b6%e0%a6%a8-%e0%a6%93-%e0%a6%a1%e0%a6%be%e0%a6%b0%e0%a7%8d%e0%a6%95-%e0%a6%b8', destination: '/shop/beaute-glutathione-skin1004-centella-brightening-combo-2pcs', permanent: true },
      { source: '/category/night-crime',   destination: '/category/night-cream', permanent: true },
      { source: '/about-us-2',            destination: '/about-us',       permanent: true },
      { source: '/about-us-2/',           destination: '/about-us',       permanent: true },
      { source: '/term-conditions',       destination: '/terms-conditions', permanent: true },
      { source: '/term-conditions/',      destination: '/terms-conditions', permanent: true },
      // WP pages found via wp post list — redirect to nearest Next.js equivalent
      { source: '/home2',                 destination: '/',                 permanent: true },
      { source: '/how-to-buy',            destination: '/faq',              permanent: true },
      { source: '/help-center',           destination: '/contact',          permanent: true },
      { source: '/shipping-delivery',     destination: '/shipping-policy',  permanent: true },
      { source: '/refund_returns',        destination: '/return-policy',    permanent: true },
      { source: '/my-orders',             destination: '/account/orders',   permanent: true },
      { source: '/dashboard',             destination: '/account',          permanent: true },
      { source: '/wishlist-2',            destination: '/wishlist',         permanent: true },
      { source: '/policy',               destination: '/return-policy',    permanent: true },
      // Duplicate product cleanup 2026-05-08 — remove slug → keep slug
      { source: '/shop/3w-clinic-collagen-luxury-gold-cream-100ml',                                              destination: '/shop/3w-clinic-collagen-and-luxury-gold-cream-100ml',                                            permanent: true },
      { source: '/shop/cerave-skin-renewing-retinol-serum-30-ml',                                                destination: '/shop/cerave-skin-renewing-retinol-serum-30ml',                                                    permanent: true },
      { source: '/shop/cerave-pm-facial-moisturizing-lotion-89-ml',                                              destination: '/shop/cerave-pm-facial-moisturizing-lotion-89ml',                                                  permanent: true },
      { source: '/shop/simple-daily-skin-detox-sos-clearing-booster-25ml-2',                                      destination: '/shop/simple-daily-skin-detox-sos-clearing-booster-25ml',                                         permanent: true },
      { source: '/shop/tiam-pore-minimizing-21-serum-40ml-3',                                                    destination: '/shop/tiam-pore-minimizing-21-serum-40ml',                                                         permanent: true },
      { source: '/shop/cos-de-baha-vitamin-c-15-serum-va-30ml',                                                  destination: '/shop/cos-de-baha-vitamin-c-15-serum-30ml',                                                       permanent: true },
      { source: '/shop/the-inkey-list-salicylic-acid-cleanser-150-ml',                                           destination: '/shop/the-inkey-list-salicylic-acid-cleanser-150ml',                                              permanent: true },
      { source: '/shop/cleanclear-night-relaxing-deep-cleaning-face-wash-240ml',                                  destination: '/shop/clean-clear-night-relaxing-deep-cleaning-face-wash-240ml',                                   permanent: true },
      { source: '/shop/neutrogena-oil-free-acne-wash-269ml-2',                                                   destination: '/shop/neutrogena-oil-free-acne-wash-269ml',                                                        permanent: true },
      { source: '/shop/neutrogena-ultra-sheer-dry-touch-sunscreen-spf-55-88ml',                                   destination: '/shop/neutrogena-ultra-sheer-dry-touch-sunscreen-spf55',                                          permanent: true },
      { source: '/shop/neutrogena-hydro-boost-water-gel-50ml',                                                   destination: '/shop/neutrogena-hydro-boost-water-gel',                                                           permanent: true },
      { source: '/shop/cos-de-baha-snail-mucin-hyaluronic-acid-serum-sh-120ml-2',                                destination: '/shop/cos-de-baha-snail-mucin-hyaluronic-acid-serum-sh-120ml',                                     permanent: true },
      { source: '/shop/raip-r3-argan-hair-oil-100-ml-original',                                                   destination: '/shop/raip-r3-argan-hair-oil-100ml',                                                               permanent: true },
      { source: '/shop/beauty-of-joseon-matte-sun-stick-mugwortcamelia-18g',                                     destination: '/shop/beauty-of-joseon-matte-sun-stick-mugwortcamelia18g-0-63fl-oz',                               permanent: true },
      { source: '/shop/medipeel-melanon-x-dark-spot-blemish-care-solution-cream-30ml',                           destination: '/shop/medi-peel-melanon-x-cream-30ml',                                                             permanent: true },
      { source: '/shop/im-from-rice-sunscreen-50ml',                                                             destination: '/shop/im-from-rice-sunscreen',                                                                     permanent: true },
      // Mary&May: keep slug is stale (was renamed); redirect still resolves to correct product ID 58048
      { source: '/shop/maryampmay-white-collagen-cleansing-foam-150ml',                                          destination: '/shop/marymay-blackberry-complex-glow-washoff-pack-125g',                                          permanent: true },
      { source: '/shop/la-roche-posay-cicaplast-baume-b5-100ml-2',                                               destination: '/shop/la-roche-posay-cicaplast-baume-b5-100ml',                                                    permanent: true },
      { source: '/shop/la-roche-posay-cicaplast-baume-b5-40ml-2',                                                destination: '/shop/la-roche-posay-cicaplast-baume-b5-40ml',                                                     permanent: true },
      { source: '/shop/im-from-black-rice-toner-150ml-2',                                                         destination: '/shop/im-from-black-rice-toner-150ml',                                                             permanent: true },
      { source: '/shop/raip-moisture-repair-body-lotion-original-500-ml',                                         destination: '/shop/raip-moisture-repair-body-lotion-500-ml',                                                    permanent: true },
      { source: '/shop/3w-clinic-charcoal-cleansing-foam100ml',                                                  destination: '/shop/3w-clinic-charcoal-cleansing-foam-100-ml',                                                   permanent: true },
      { source: '/shop/oriox-color-lip-balm-4-8g-cherry-2',                                                     destination: '/shop/oriox-color-lip-balm-4-8g-cherry',                                                          permanent: true },
      { source: '/shop/daiso-glucosamine-supplement-15-days-30-tablet-2',                                        destination: '/shop/daiso-glucosamine-supplement-15-days-30-tablet',                                             permanent: true },
      { source: '/shop/everly-matte-me-up-lip-liner-pencil-dark-brown-1-5g-2',                                   destination: '/shop/everly-matte-me-up-lip-liner-pencil-dark-brown-1-5g',                                        permanent: true },
      { source: '/shop/kiss-beauty-bling-bling-liquid-highlighter-01-40ml-2',                                     destination: '/shop/kiss-beauty-bling-bling-liquid-highlighter-01-40ml',                                         permanent: true },
      { source: '/shop/l-a-girl-pro-matte-liquid-foundation-glm715porcelain-30ml-2',                              destination: '/shop/l-a-girl-pro-matte-liquid-foundation-glm715porcelain-30ml',                                permanent: true },
      { source: '/shop/lmltop-beauty-makeup-tools-2pcs-puff-2',                                                   destination: '/shop/lmltop-beauty-makeup-tools-2pcs-puff',                                                       permanent: true },
      { source: '/shop/maange-12pcs-mix-makeup-brush-set-white-2',                                               destination: '/shop/maange-12pcs-mix-makeup-brush-set-white',                                                    permanent: true },
      { source: '/shop/maybelline-super-stay-matte-ink-liquid-lipstick-117-ground-breaker-5ml-2',                destination: '/shop/maybelline-super-stay-matte-ink-liquid-lipstick-117-ground-breaker-5ml',                     permanent: true },
      { source: '/shop/pinkflash-lasting-matte-foundation-pf-f03-vanilla-01-25g-2',                              destination: '/shop/pinkflash-lasting-matte-foundation-pf-f03-vanilla-01-25g',                                  permanent: true },
      { source: '/shop/rohto-acnes-foaming-face-wash-160ml-2',                                                   destination: '/shop/rohto-acnes-foaming-face-wash-160ml',                                                        permanent: true },
      // Slug dedup cleanup 2026-05-08 — -2/copy suffix removed from 68 live products
      { source: '/shop/cerave-skin-renewing-retinol-serum-30ml-2', destination: '/shop/cerave-skin-renewing-retinol-serum-30ml', permanent: true },
      { source: '/product/cerave-skin-renewing-retinol-serum-30ml-2', destination: '/shop/cerave-skin-renewing-retinol-serum-30ml', permanent: true },
      { source: '/shop/secret-key-snow-white-milky-pack-120g-2', destination: '/shop/secret-key-snow-white-milky-pack-120g', permanent: true },
      { source: '/product/secret-key-snow-white-milky-pack-120g-2', destination: '/shop/secret-key-snow-white-milky-pack-120g', permanent: true },
      { source: '/shop/confume-argan-smoothing-hair-essence-500-gm-2', destination: '/shop/confume-argan-smoothing-hair-essence-500-gm', permanent: true },
      { source: '/product/confume-argan-smoothing-hair-essence-500-gm-2', destination: '/shop/confume-argan-smoothing-hair-essence-500-gm', permanent: true },
      { source: '/shop/confume-argan-treatment-oil-120-ml-25-ml-2', destination: '/shop/confume-argan-treatment-oil-120-ml-25-ml', permanent: true },
      { source: '/product/confume-argan-treatment-oil-120-ml-25-ml-2', destination: '/shop/confume-argan-treatment-oil-120-ml-25-ml', permanent: true },
      { source: '/shop/tiam-anti-blemish-body-lotion-200ml-2', destination: '/shop/tiam-anti-blemish-body-lotion-200ml', permanent: true },
      { source: '/product/tiam-anti-blemish-body-lotion-200ml-2', destination: '/shop/tiam-anti-blemish-body-lotion-200ml', permanent: true },
      { source: '/shop/simple-protect-n-glow-rest-and-reset-72h-hydrating-gel-50ml-2', destination: '/shop/simple-protect-n-glow-rest-and-reset-72h-hydrating-gel-50ml', permanent: true },
      { source: '/product/simple-protect-n-glow-rest-and-reset-72h-hydrating-gel-50ml-2', destination: '/shop/simple-protect-n-glow-rest-and-reset-72h-hydrating-gel-50ml', permanent: true },
      { source: '/shop/im-from-rice-serum-30ml-2', destination: '/shop/im-from-rice-serum-30ml', permanent: true },
      { source: '/product/im-from-rice-serum-30ml-2', destination: '/shop/im-from-rice-serum-30ml', permanent: true },
      { source: '/shop/skinfood-yuja-c-dark-spot-clear-cream-2', destination: '/shop/skinfood-yuja-c-dark-spot-clear-cream', permanent: true },
      { source: '/product/skinfood-yuja-c-dark-spot-clear-cream-2', destination: '/shop/skinfood-yuja-c-dark-spot-clear-cream', permanent: true },
      { source: '/shop/skinfood-yuja-c-dark-spot-clear-essence-2', destination: '/shop/skinfood-yuja-c-dark-spot-clear-essence', permanent: true },
      { source: '/product/skinfood-yuja-c-dark-spot-clear-essence-2', destination: '/shop/skinfood-yuja-c-dark-spot-clear-essence', permanent: true },
      { source: '/shop/hts-anti-hair-loss-scalp-tonic-150ml-2', destination: '/shop/hts-anti-hair-loss-scalp-tonic-150ml', permanent: true },
      { source: '/product/hts-anti-hair-loss-scalp-tonic-150ml-2', destination: '/shop/hts-anti-hair-loss-scalp-tonic-150ml', permanent: true },
      { source: '/shop/claires-guerisson-9-complex-cream-70g-2', destination: '/shop/claires-guerisson-9-complex-cream-70g', permanent: true },
      { source: '/product/claires-guerisson-9-complex-cream-70g-2', destination: '/shop/claires-guerisson-9-complex-cream-70g', permanent: true },
      { source: '/shop/rovectin-travel-kit-4-step-2', destination: '/shop/rovectin-travel-kit-4-step', permanent: true },
      { source: '/product/rovectin-travel-kit-4-step-2', destination: '/shop/rovectin-travel-kit-4-step', permanent: true },
      { source: '/shop/buy-cos-de-baha-acne-clearing-serum-acne-treatment-30ml-2', destination: '/shop/buy-cos-de-baha-acne-clearing-serum-acne-treatment-30ml', permanent: true },
      { source: '/product/buy-cos-de-baha-acne-clearing-serum-acne-treatment-30ml-2', destination: '/shop/buy-cos-de-baha-acne-clearing-serum-acne-treatment-30ml', permanent: true },
      { source: '/shop/cos-de-baha-centella-asiatica-facial-serum-ch-30ml-2', destination: '/shop/cos-de-baha-centella-asiatica-facial-serum-ch-30ml', permanent: true },
      { source: '/product/cos-de-baha-centella-asiatica-facial-serum-ch-30ml-2', destination: '/shop/cos-de-baha-centella-asiatica-facial-serum-ch-30ml', permanent: true },
      { source: '/shop/cos-de-baha-aha-serum-60ml-n60-2', destination: '/shop/cos-de-baha-aha-serum-60ml-n60', permanent: true },
      { source: '/product/cos-de-baha-aha-serum-60ml-n60-2', destination: '/shop/cos-de-baha-aha-serum-60ml-n60', permanent: true },
      { source: '/shop/innisfree-perfect-9-repair-cream-ex-60ml-2', destination: '/shop/innisfree-perfect-9-repair-cream-ex-60ml', permanent: true },
      { source: '/product/innisfree-perfect-9-repair-cream-ex-60ml-2', destination: '/shop/innisfree-perfect-9-repair-cream-ex-60ml', permanent: true },
      { source: '/shop/some-by-mi-super-matcha-pore-clean-cleansing-gel-100ml-2', destination: '/shop/some-by-mi-super-matcha-pore-clean-cleansing-gel-100ml', permanent: true },
      { source: '/product/some-by-mi-super-matcha-pore-clean-cleansing-gel-100ml-2', destination: '/shop/some-by-mi-super-matcha-pore-clean-cleansing-gel-100ml', permanent: true },
      { source: '/shop/some-by-mi-super-matcha-pore-care-starter-kit-4pcs-2', destination: '/shop/some-by-mi-super-matcha-pore-care-starter-kit-4pcs', permanent: true },
      { source: '/product/some-by-mi-super-matcha-pore-care-starter-kit-4pcs-2', destination: '/shop/some-by-mi-super-matcha-pore-care-starter-kit-4pcs', permanent: true },
      { source: '/shop/melasma-x-glutathione-water-drop-skin-toner-260ml-2', destination: '/shop/melasma-x-glutathione-water-drop-skin-toner-260ml', permanent: true },
      { source: '/product/melasma-x-glutathione-water-drop-skin-toner-260ml-2', destination: '/shop/melasma-x-glutathione-water-drop-skin-toner-260ml', permanent: true },
      { source: '/shop/melasma-x-moringa-brightening-cool-soothing-gel-160ml-2', destination: '/shop/melasma-x-moringa-brightening-cool-soothing-gel-160ml', permanent: true },
      { source: '/product/melasma-x-moringa-brightening-cool-soothing-gel-160ml-2', destination: '/shop/melasma-x-moringa-brightening-cool-soothing-gel-160ml', permanent: true },
      { source: '/shop/beaute-24k-meladoctor-white-gold-repair-ampoule-30ml-2', destination: '/shop/beaute-24k-meladoctor-white-gold-repair-ampoule-30ml', permanent: true },
      { source: '/product/beaute-24k-meladoctor-white-gold-repair-ampoule-30ml-2', destination: '/shop/beaute-24k-meladoctor-white-gold-repair-ampoule-30ml', permanent: true },
      { source: '/shop/thank-you-farmer-rice-pure-clay-mask-to-foam-cleanser-150ml-2', destination: '/shop/thank-you-farmer-rice-pure-clay-mask-to-foam-cleanser-150ml', permanent: true },
      { source: '/product/thank-you-farmer-rice-pure-clay-mask-to-foam-cleanser-150ml-2', destination: '/shop/thank-you-farmer-rice-pure-clay-mask-to-foam-cleanser-150ml', permanent: true },
      { source: '/shop/thank-you-farmer-safe-sun-fluid-age-0880-spf50-pa-2', destination: '/shop/thank-you-farmer-safe-sun-fluid-age-0880-spf50-pa', permanent: true },
      { source: '/product/thank-you-farmer-safe-sun-fluid-age-0880-spf50-pa-2', destination: '/shop/thank-you-farmer-safe-sun-fluid-age-0880-spf50-pa', permanent: true },
      { source: '/shop/thank-you-farmer-sun-project-light-sun-essence-spf50-pa-40ml-2', destination: '/shop/thank-you-farmer-sun-project-light-sun-essence-spf50-pa-40ml', permanent: true },
      { source: '/product/thank-you-farmer-sun-project-light-sun-essence-spf50-pa-40ml-2', destination: '/shop/thank-you-farmer-sun-project-light-sun-essence-spf50-pa-40ml', permanent: true },
      { source: '/shop/mise-en-scene-golden-morocco-argan-oil-shampoo-680-ml-2', destination: '/shop/mise-en-scene-golden-morocco-argan-oil-shampoo-680-ml', permanent: true },
      { source: '/product/mise-en-scene-golden-morocco-argan-oil-shampoo-680-ml-2', destination: '/shop/mise-en-scene-golden-morocco-argan-oil-shampoo-680-ml', permanent: true },
      { source: '/shop/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant-30ml-2', destination: '/shop/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant-30ml', permanent: true },
      { source: '/product/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant-30ml-2', destination: '/shop/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant-30ml', permanent: true },
      { source: '/shop/farm-stay-cica-farm-nature-solution-cleansing-foam-180ml-2', destination: '/shop/farm-stay-cica-farm-nature-solution-cleansing-foam-180ml', permanent: true },
      { source: '/product/farm-stay-cica-farm-nature-solution-cleansing-foam-180ml-2', destination: '/shop/farm-stay-cica-farm-nature-solution-cleansing-foam-180ml', permanent: true },
      { source: '/shop/3w-clinic-relaxing-body-lotion-camellia-550ml-2', destination: '/shop/3w-clinic-relaxing-body-lotion-camellia-550ml', permanent: true },
      { source: '/product/3w-clinic-relaxing-body-lotion-camellia-550ml-2', destination: '/shop/3w-clinic-relaxing-body-lotion-camellia-550ml', permanent: true },
      { source: '/shop/the-face-shop-herb-day-365-master-blending-foaming-cleanser-peach-fig-170ml-2', destination: '/shop/the-face-shop-herb-day-365-master-blending-foaming-cleanser-peach-fig-170ml', permanent: true },
      { source: '/product/the-face-shop-herb-day-365-master-blending-foaming-cleanser-peach-fig-170ml-2', destination: '/shop/the-face-shop-herb-day-365-master-blending-foaming-cleanser-peach-fig-170ml', permanent: true },
      { source: '/shop/the-face-shop-herbday-365-cleansing-foam-aloe-green-tea-170ml-2', destination: '/shop/the-face-shop-herbday-365-cleansing-foam-aloe-green-tea-170ml', permanent: true },
      { source: '/product/the-face-shop-herbday-365-cleansing-foam-aloe-green-tea-170ml-2', destination: '/shop/the-face-shop-herbday-365-cleansing-foam-aloe-green-tea-170ml', permanent: true },
      { source: '/shop/mise-en-scene-scalp-care-shampoo-680ml-2', destination: '/shop/mise-en-scene-scalp-care-shampoo-680ml', permanent: true },
      { source: '/product/mise-en-scene-scalp-care-shampoo-680ml-2', destination: '/shop/mise-en-scene-scalp-care-shampoo-680ml', permanent: true },
      { source: '/shop/dabo-elegance-love-body-lotion-500ml-2', destination: '/shop/dabo-elegance-love-body-lotion-500ml', permanent: true },
      { source: '/product/dabo-elegance-love-body-lotion-500ml-2', destination: '/shop/dabo-elegance-love-body-lotion-500ml', permanent: true },
      { source: '/shop/dabo-white-musk-body-lotion-500ml-2', destination: '/shop/dabo-white-musk-body-lotion-500ml', permanent: true },
      { source: '/product/dabo-white-musk-body-lotion-500ml-2', destination: '/shop/dabo-white-musk-body-lotion-500ml', permanent: true },
      { source: '/shop/dabo-uv-protection-collagen-lifting-sun-cream-spf50-pa-70ml-2', destination: '/shop/dabo-uv-protection-collagen-lifting-sun-cream-spf50-pa-70ml', permanent: true },
      { source: '/product/dabo-uv-protection-collagen-lifting-sun-cream-spf50-pa-70ml-2', destination: '/shop/dabo-uv-protection-collagen-lifting-sun-cream-spf50-pa-70ml', permanent: true },
      { source: '/shop/dabo-s-o-s-recovery-cica-cream-50ml-2', destination: '/shop/dabo-s-o-s-recovery-cica-cream-50ml', permanent: true },
      { source: '/product/dabo-s-o-s-recovery-cica-cream-50ml-2', destination: '/shop/dabo-s-o-s-recovery-cica-cream-50ml', permanent: true },
      { source: '/shop/dabo-slimming-hot-gel-anti-cellulite-slim-body-massage-cream-200g-2', destination: '/shop/dabo-slimming-hot-gel-anti-cellulite-slim-body-massage-cream-200g', permanent: true },
      { source: '/product/dabo-slimming-hot-gel-anti-cellulite-slim-body-massage-cream-200g-2', destination: '/shop/dabo-slimming-hot-gel-anti-cellulite-slim-body-massage-cream-200g', permanent: true },
      { source: '/shop/dabo-eco-lifestyle-premium-cc-cream-spf50-pa-50ml-2', destination: '/shop/dabo-eco-lifestyle-premium-cc-cream-spf50-pa-50ml', permanent: true },
      { source: '/product/dabo-eco-lifestyle-premium-cc-cream-spf50-pa-50ml-2', destination: '/shop/dabo-eco-lifestyle-premium-cc-cream-spf50-pa-50ml', permanent: true },
      { source: '/shop/dabo-collagen-lifting-eye-cream-for-face-30ml-2', destination: '/shop/dabo-collagen-lifting-eye-cream-for-face-30ml', permanent: true },
      { source: '/product/dabo-collagen-lifting-eye-cream-for-face-30ml-2', destination: '/shop/dabo-collagen-lifting-eye-cream-for-face-30ml', permanent: true },
      { source: '/shop/nella-oneday-whitener-magical-whitening-lotion-40ml-2', destination: '/shop/nella-oneday-whitener-magical-whitening-lotion-40ml', permanent: true },
      { source: '/product/nella-oneday-whitener-magical-whitening-lotion-40ml-2', destination: '/shop/nella-oneday-whitener-magical-whitening-lotion-40ml', permanent: true },
      { source: '/shop/rovectin-clean-marine-micellar-deep-cleansing-water-400ml-2', destination: '/shop/rovectin-clean-marine-micellar-deep-cleansing-water-400ml', permanent: true },
      { source: '/product/rovectin-clean-marine-micellar-deep-cleansing-water-400ml-2', destination: '/shop/rovectin-clean-marine-micellar-deep-cleansing-water-400ml', permanent: true },
      { source: '/shop/kosmedica-organic-clean-gel-intimate-wash-80gm-2', destination: '/shop/kosmedica-organic-clean-gel-intimate-wash-80gm', permanent: true },
      { source: '/product/kosmedica-organic-clean-gel-intimate-wash-80gm-2', destination: '/shop/kosmedica-organic-clean-gel-intimate-wash-80gm', permanent: true },
      { source: '/shop/pax-moly-honey-radiant-glow-cream-100g-2', destination: '/shop/pax-moly-honey-radiant-glow-cream-100g', permanent: true },
      { source: '/product/pax-moly-honey-radiant-glow-cream-100g-2', destination: '/shop/pax-moly-honey-radiant-glow-cream-100g', permanent: true },
      { source: '/shop/jumiso-rich-nourishment-sheet-mask-26ml-2', destination: '/shop/jumiso-rich-nourishment-sheet-mask-26ml', permanent: true },
      { source: '/product/jumiso-rich-nourishment-sheet-mask-26ml-2', destination: '/shop/jumiso-rich-nourishment-sheet-mask-26ml', permanent: true },
      { source: '/shop/welcos-body-phren-shower-gel-oriental-rose-732g-2', destination: '/shop/welcos-body-phren-shower-gel-oriental-rose-732g', permanent: true },
      { source: '/product/welcos-body-phren-shower-gel-oriental-rose-732g-2', destination: '/shop/welcos-body-phren-shower-gel-oriental-rose-732g', permanent: true },
      { source: '/shop/medb-daily-snail-cream-100ml-2', destination: '/shop/medb-daily-snail-cream-100ml', permanent: true },
      { source: '/product/medb-daily-snail-cream-100ml-2', destination: '/shop/medb-daily-snail-cream-100ml', permanent: true },
      { source: '/shop/3w-clinic-enrich-lovely-foot-cream-100ml-2', destination: '/shop/3w-clinic-enrich-lovely-foot-cream-100ml', permanent: true },
      { source: '/product/3w-clinic-enrich-lovely-foot-cream-100ml-2', destination: '/shop/3w-clinic-enrich-lovely-foot-cream-100ml', permanent: true },
      { source: '/shop/skylake-oriental-herb-houttuynia-cordata-hair-tonic-2', destination: '/shop/skylake-oriental-herb-houttuynia-cordata-hair-tonic', permanent: true },
      { source: '/product/skylake-oriental-herb-houttuynia-cordata-hair-tonic-2', destination: '/shop/skylake-oriental-herb-houttuynia-cordata-hair-tonic', permanent: true },
      { source: '/shop/sonpark-beauty-water-mini-60ml-2', destination: '/shop/sonpark-beauty-water-mini-60ml', permanent: true },
      { source: '/product/sonpark-beauty-water-mini-60ml-2', destination: '/shop/sonpark-beauty-water-mini-60ml', permanent: true },
      { source: '/shop/heeyul-premium-24k-gold-ampoule-cream-2', destination: '/shop/heeyul-premium-24k-gold-ampoule-cream', permanent: true },
      { source: '/product/heeyul-premium-24k-gold-ampoule-cream-2', destination: '/shop/heeyul-premium-24k-gold-ampoule-cream', permanent: true },
      { source: '/shop/some-by-mi-charcoal-bha-pore-clay-bubble-mask-50ml-2', destination: '/shop/some-by-mi-charcoal-bha-pore-clay-bubble-mask-50ml', permanent: true },
      { source: '/product/some-by-mi-charcoal-bha-pore-clay-bubble-mask-50ml-2', destination: '/shop/some-by-mi-charcoal-bha-pore-clay-bubble-mask-50ml', permanent: true },
      { source: '/shop/benton-tea-tree-serum-30ml-2', destination: '/shop/benton-tea-tree-serum-30ml', permanent: true },
      { source: '/product/benton-tea-tree-serum-30ml-2', destination: '/shop/benton-tea-tree-serum-30ml', permanent: true },
      { source: '/shop/benton-snail-bee-ultimate-serum-35-ml-2', destination: '/shop/benton-snail-bee-ultimate-serum-35-ml', permanent: true },
      { source: '/product/benton-snail-bee-ultimate-serum-35-ml-2', destination: '/shop/benton-snail-bee-ultimate-serum-35-ml', permanent: true },
      { source: '/shop/benton-goodbye-redness-centella-spot-cream-15ml-2', destination: '/shop/benton-goodbye-redness-centella-spot-cream-15ml', permanent: true },
      { source: '/product/benton-goodbye-redness-centella-spot-cream-15ml-2', destination: '/shop/benton-goodbye-redness-centella-spot-cream-15ml', permanent: true },
      { source: '/shop/the-inkey-list-salicylic-acid-cleanser-150ml-2', destination: '/shop/the-inkey-list-salicylic-acid-cleanser-150ml', permanent: true },
      { source: '/product/the-inkey-list-salicylic-acid-cleanser-150ml-2', destination: '/shop/the-inkey-list-salicylic-acid-cleanser-150ml', permanent: true },
      { source: '/shop/the-inkey-list-succinic-acid-blemish-treatment-15ml-2', destination: '/shop/the-inkey-list-succinic-acid-blemish-treatment-15ml', permanent: true },
      { source: '/product/the-inkey-list-succinic-acid-blemish-treatment-15ml-2', destination: '/shop/the-inkey-list-succinic-acid-blemish-treatment-15ml', permanent: true },
      { source: '/shop/the-inkey-list-lactic-acid-serum-30ml-2', destination: '/shop/the-inkey-list-lactic-acid-serum-30ml', permanent: true },
      { source: '/product/the-inkey-list-lactic-acid-serum-30ml-2', destination: '/shop/the-inkey-list-lactic-acid-serum-30ml', permanent: true },
      { source: '/shop/jigott-goat-milk-whitening-cream-70ml-2', destination: '/shop/jigott-goat-milk-whitening-cream-70ml', permanent: true },
      { source: '/product/jigott-goat-milk-whitening-cream-70ml-2', destination: '/shop/jigott-goat-milk-whitening-cream-70ml', permanent: true },
      { source: '/shop/innisfree-black-tea-trial-kit-4pcs-2', destination: '/shop/innisfree-black-tea-trial-kit-4pcs', permanent: true },
      { source: '/product/innisfree-black-tea-trial-kit-4pcs-2', destination: '/shop/innisfree-black-tea-trial-kit-4pcs', permanent: true },
      { source: '/shop/innisfree-black-tea-youth-enhancing-ampoule-30-ml-2', destination: '/shop/innisfree-black-tea-youth-enhancing-ampoule-30-ml', permanent: true },
      { source: '/product/innisfree-black-tea-youth-enhancing-ampoule-30-ml-2', destination: '/shop/innisfree-black-tea-youth-enhancing-ampoule-30-ml', permanent: true },
      { source: '/shop/cerave-foaming-cleanser-for-normal-to-oily-skin-236ml-2', destination: '/shop/cerave-foaming-cleanser-for-normal-to-oily-skin-236ml', permanent: true },
      { source: '/product/cerave-foaming-cleanser-for-normal-to-oily-skin-236ml-2', destination: '/shop/cerave-foaming-cleanser-for-normal-to-oily-skin-236ml', permanent: true },
      { source: '/shop/banila-co-clean-it-zero-cleansing-balm-nourishing-100ml-2', destination: '/shop/banila-co-clean-it-zero-cleansing-balm-nourishing-100ml', permanent: true },
      { source: '/product/banila-co-clean-it-zero-cleansing-balm-nourishing-100ml-2', destination: '/shop/banila-co-clean-it-zero-cleansing-balm-nourishing-100ml', permanent: true },
      { source: '/shop/some-by-mi-total-care-serum-trial-kit-4pcs-2', destination: '/shop/some-by-mi-total-care-serum-trial-kit-4pcs', permanent: true },
      { source: '/product/some-by-mi-total-care-serum-trial-kit-4pcs-2', destination: '/shop/some-by-mi-total-care-serum-trial-kit-4pcs', permanent: true },
      { source: '/shop/m-a-c-amplified-lipstick-vegas-volt-3gm-2', destination: '/shop/m-a-c-amplified-lipstick-vegas-volt-3gm', permanent: true },
      { source: '/product/m-a-c-amplified-lipstick-vegas-volt-3gm-2', destination: '/shop/m-a-c-amplified-lipstick-vegas-volt-3gm', permanent: true },
      { source: '/shop/nature-republic-soothing-moisture-aloe-vera-92-soothing-gel-2', destination: '/shop/nature-republic-soothing-moisture-aloe-vera-92-soothing-gel', permanent: true },
      { source: '/product/nature-republic-soothing-moisture-aloe-vera-92-soothing-gel-2', destination: '/shop/nature-republic-soothing-moisture-aloe-vera-92-soothing-gel', permanent: true },
      { source: '/shop/anua-heartleaf-pore-control-cleansing-oil-200ml-2', destination: '/shop/anua-heartleaf-pore-control-cleansing-oil-200ml', permanent: true },
      { source: '/product/anua-heartleaf-pore-control-cleansing-oil-200ml-2', destination: '/shop/anua-heartleaf-pore-control-cleansing-oil-200ml', permanent: true },
      { source: '/shop/beauty-of-joseon-red-bean-water-gel-100ml-2', destination: '/shop/beauty-of-joseon-red-bean-water-gel-100ml', permanent: true },
      { source: '/product/beauty-of-joseon-red-bean-water-gel-100ml-2', destination: '/shop/beauty-of-joseon-red-bean-water-gel-100ml', permanent: true },
      { source: '/shop/medicube-zero-pore-cream-50ml-2', destination: '/shop/medicube-zero-pore-cream-50ml', permanent: true },
      { source: '/product/medicube-zero-pore-cream-50ml-2', destination: '/shop/medicube-zero-pore-cream-50ml', permanent: true },
      { source: '/shop/karite-bubble-pink-mud-mask-5ml-2', destination: '/shop/karite-bubble-pink-mud-mask-5ml', permanent: true },
      { source: '/product/karite-bubble-pink-mud-mask-5ml-2', destination: '/shop/karite-bubble-pink-mud-mask-5ml', permanent: true },
      { source: '/shop/aplb-glutathione-niacinamide-body-lotion-300ml-copy', destination: '/shop/aplb-glutathione-niacinamide-body-lotion-300ml', permanent: true },
      { source: '/product/aplb-glutathione-niacinamide-body-lotion-300ml-copy', destination: '/shop/aplb-glutathione-niacinamide-body-lotion-300ml', permanent: true },
      // Old WooCommerce concern categories → canonical concern pages (2026-05-13)
      // These /category/* URLs are superseded by /concerns/* SEO pages.
      // The WooCommerce taxonomy stays intact for product assignment; only the public URL changes.
      { source: '/category/shop-by-concern',   destination: '/concerns',                        permanent: true },
      { source: '/category/acne-blemish-care', destination: '/concerns/acne-blemish-care',      permanent: true },
      { source: '/category/anti-aging-repair', destination: '/concerns/anti-aging-repair',      permanent: true },
      { source: '/category/dryness-hydration', destination: '/concerns/dryness-hydration',      permanent: true },
      { source: '/category/pores-oil-control', destination: '/concerns/pores-oil-control',      permanent: true },
      { source: '/category/melasma',           destination: '/concerns/melasma',                permanent: true },
      { source: '/category/brightening',       destination: '/concerns/brightening',            permanent: true },
      { source: '/category/wrinkle',           destination: '/concerns/wrinkle',               permanent: true },
      { source: '/category/sensitivity',       destination: '/concerns/sensitivity',            permanent: true },
      // Broad parent/grouping categories with no useful standalone page → /shop
      { source: '/category/skincare-essentials', destination: '/shop',                          permanent: true },
      { source: '/category/k-beauty-j-beauty',   destination: '/category/korean-beauty',        permanent: true },
      { source: '/category/shooting-gel',         destination: '/category/soothing-gel',         permanent: true },
      // Celimax Meta ad broken slug — missing separator, 404 in GSC; redirect to serum
      { source: '/shop/celimax-poredark-spot', destination: '/shop/celimax-poredark-spot-brightening-serum-30ml', permanent: true },

      // ── GSC 404 cleanup 2026-05-16 ──────────────────────────────────────────

      // Old WordPress blog date-based URLs → blog index (15 URLs, one rule)
      { source: '/:year(20\\d{2})/:month(\\d{2})/:day(\\d{2})/:slug*', destination: '/blog', permanent: true },

      // Old /brand/ (singular) → /brands/
      { source: '/brand/:slug*', destination: '/brands/:slug*', permanent: true },

      // Brand aliases not yet covered
      { source: '/brands/i\'m-from',             destination: '/brands/im-from',          permanent: true },
      { source: '/brands/i-m-from',              destination: '/brands/im-from',           permanent: true },
      { source: '/brands/dr-jart',               destination: '/brands/dr-jart-plus',      permanent: true },

      // Brand pages that have no products or are discontinued → /shop
      { source: '/brands/beaute-moringa-melasma', destination: '/shop',                   permanent: true },
      { source: '/brands/japanese',               destination: '/category/japanese-beauty', permanent: true },
      { source: '/brands/green',                  destination: '/shop',                   permanent: true },
      { source: '/brands/valencia',               destination: '/shop',                   permanent: true },
      { source: '/brands/sensitive',              destination: '/shop',                   permanent: true },
      { source: '/brands/absolute',               destination: '/shop',                   permanent: true },
      { source: '/brands/cellpod',                destination: '/shop',                   permanent: true },
      { source: '/brands/ruthair',                destination: '/shop',                   permanent: true },
      { source: '/brands/kao',                    destination: '/shop',                   permanent: true },
      { source: '/brands/nizoral',                destination: '/shop',                   permanent: true },
      { source: '/brands/ottogi',                 destination: '/shop',                   permanent: true },
      { source: '/brands/labelyoung',             destination: '/shop',                   permanent: true },
      { source: '/brands/syoss',                  destination: '/shop',                   permanent: true },
      { source: '/brands/radiant',                destination: '/shop',                   permanent: true },
      { source: '/brands/tresemm',                destination: '/shop',                   permanent: true },
      { source: '/brands/karite',                 destination: '/shop',                   permanent: true },
      { source: '/brands/healthy-place',          destination: '/shop',                   permanent: true },
      { source: '/brands/the',                    destination: '/shop',                   permanent: true },
      { source: '/brands/daily',                  destination: '/shop',                   permanent: true },
      { source: '/brands/bath',                   destination: '/shop',                   permanent: true },
      { source: '/brands/house',                  destination: '/shop',                   permanent: true },
      { source: '/brands/innsaei',                destination: '/shop',                   permanent: true },
      { source: '/brands/skino',                  destination: '/shop',                   permanent: true },
      { source: '/brands/lucido',                 destination: '/shop',                   permanent: true },
      { source: '/brands/laxzin',                 destination: '/shop',                   permanent: true },
      { source: '/brands/beauty',                 destination: '/shop',                   permanent: true },
      { source: '/brands/wishcare',               destination: '/shop',                   permanent: true },
      { source: '/brands/sadoer',                 destination: '/shop',                   permanent: true },

      // Category aliases not yet covered
      { source: '/category/skincare/melasma',         destination: '/concerns/melasma',         permanent: true },
      { source: '/category/skincare/acne',            destination: '/concerns/acne-blemish-care', permanent: true },
      { source: '/category/skincare/j-beauty-skincare', destination: '/category/japanese-beauty', permanent: true },
      { source: '/category/top-cosmetics-ingredients', destination: '/ingredients',              permanent: true },
      { source: '/category/life-style',               destination: '/',                          permanent: true },

      // Specific broken shop slugs (underscore/encoding variants)
      { source: '/shop/b_lab-matcha-hydrating-real-sun-stick-21g',   destination: '/shop/b-lab-matcha-hydrating-real-sun-stick-21g',  permanent: true },
      { source: '/shop/round-lab-eng-1025-dokdo-ampule_45g',         destination: '/shop/round-lab-1025-dokdo-ampule',               permanent: true },
      { source: '/shop/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant-118ml', destination: '/shop/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant', permanent: true },

      // Junk/old WordPress routes
      { source: '/elementor-:id',                 destination: '/',    permanent: true },
      { source: '/product-brand/:slug*',          destination: '/shop', permanent: true },
    ];
  },

  images: {
    unoptimized: false,
    minimumCacheTTL: 2678400,
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    remotePatterns: [
      { protocol: 'https', hostname: 'e-mart.com.bd' },
      { protocol: 'https', hostname: 'www.e-mart.com.bd' },
      { protocol: 'https', hostname: '**.woocommerce.com' },
      { protocol: 'https', hostname: 'img.youtube.com' },
    ],
  },

  experimental: {
    optimizePackageImports: ['lucide-react'],
  },
};
module.exports = nextConfig;
