export const STORE_POLICIES = {
  shipping: {
    orderCutoff: '6:00 PM Bangladesh time',
    dhakaDelivery: 'Dhaka 1–2 business days',
    outsideDhakaDelivery: 'usually 3–5 business days',
    overallDeliveryEstimate: '1–6 business days',
    dhakaShippingFee: 70,
    outsideDhakaShippingFee: 100,
    merchantCenterFlatShippingFee: 100,
    freeShippingThreshold: 3000,
    codAvailableAcrossBangladesh: true,
    pdpDeliveryText: 'Dhaka 1–2 business days · Outside Dhaka 3–5 business days',
    compactDeliveryText: '1–6 business days',
    checkoutFeeText: 'Final delivery fee is shown at checkout.',
    headerBannerText: 'Dhaka 1–2 business days · Outside Dhaka 3–5 business days · COD available',
    footerTrustText: 'Delivery fee shown at checkout · Dhaka 1–2 business days · Outside Dhaka 3–5 business days',
  },
  returns: {
    returnWindow: '7 days from delivery',
    acceptedReturns: 'defective and non-defective products',
    exchanges: 'accepted',
    productCondition: 'new, unused, unopened, original seal/packaging intact',
    returnMethod: 'by mail/courier',
    returnCourierCost: 'customer responsibility',
    restockingFee: '৳100 fixed cost',
    restockingFeeAmount: 100,
    refundProcessingTime: '5 days after inspection',
  },
} as const;
