import React from 'react';
import { Text } from 'react-native';

const ICON_GLYPHS = {
  add: '+',
  'airplane-outline': '^',
  'apps-outline': '#',
  'arrow-back': '<',
  'arrow-down-outline': 'v',
  'arrow-forward': '>',
  'arrow-up-outline': '^',
  'bicycle-outline': 'b',
  'book-outline': 'B',
  'business-outline': 'B',
  'call-outline': 'T',
  'card-outline': 'C',
  'car-outline': 'D',
  'cart-outline': 'c',
  'cash-outline': '৳',
  'chatbubble-outline': '"',
  checkmark: '✓',
  'checkmark-circle': '✓',
  'checkmark-circle-outline': '✓',
  'chevron-forward': '>',
  'clipboard-outline': 'Q',
  'close-circle': '×',
  'close-circle-outline': '×',
  'create-outline': '+',
  'cube-outline': '□',
  'document-text-outline': '≡',
  'ellipse-outline': '○',
  'eye-off-outline': '⊘',
  'eye-outline': '◉',
  flash: '!',
  'flash-outline': '!',
  'flame-outline': '▲',
  'globe-outline': '◎',
  grid: '#',
  'grid-outline': '#',
  'heart-outline': '♡',
  'help-circle-outline': '?',
  'hourglass-outline': '⌁',
  'image-outline': '□',
  'information-circle-outline': 'i',
  language: '文',
  'language-outline': '文',
  layers: '#',
  'list-outline': '≡',
  'location-outline': '⌖',
  'lock-closed-outline': '●',
  'logo-facebook': 'f',
  'logo-whatsapp': 'w',
  'mail-outline': '@',
  medical: '+',
  'medical-outline': '+',
  medkit: '+',
  'medkit-outline': '+',
  notifications: '!',
  'notifications-off-outline': '!',
  'notifications-outline': '!',
  person: '○',
  'person-add-outline': '+',
  'person-outline': '○',
  'phone-portrait-outline': '▯',
  pricetag: '$',
  'pricetag-outline': '$',
  receipt: '#',
  'receipt-outline': '#',
  'refresh-outline': '↻',
  'return-down-back-outline': '↩',
  'search': '⌕',
  'search-outline': '⌕',
  'settings-outline': '⚙',
  'share-outline': '^',
  'shield-checkmark-outline': '✓',
  'sparkles': '*',
  'sparkles-outline': '*',
  'star-outline': '*',
  'sunny-outline': '*',
  'swap-vertical': '↕',
  'time-outline': '◷',
  'trash-outline': '×',
  'trophy-outline': 'T',
  'water-outline': '•',
};

export default function AppIcon({ name, size = 18, color = '#000', style }) {
  const glyph = ICON_GLYPHS[name] || '?';

  return (
    <Text
      allowFontScaling={false}
      style={[
        {
          color,
          fontSize: size,
          lineHeight: size + 2,
          fontWeight: '800',
          textAlign: 'center',
          includeFontPadding: false,
          minWidth: size,
        },
        style,
      ]}
    >
      {glyph}
    </Text>
  );
}
