// Curated brand whitelist sourced from skincarebd.com /brands taxonomy (April 2026).
// Used to filter the noisy WooCommerce `pa_brand` attribute terms (which include
// product-specific entries like "Abib Airy Sunstick") down to canonical brand names.
//
// Each entry: canonical display name + array of slug aliases. Slug = lowercase,
// alphanumerics only, hyphen-separated. WC term slug must match one of the aliases.

export interface CanonicalBrand {
  name: string;
  region: 'korean' | 'western';
  slugs: string[];
}

export const CANONICAL_BRANDS: CanonicalBrand[] = [
  { name: '3W Clinic', region: 'korean', slugs: ['3w-clinic', '3w-clinic-1'] },
  { name: 'ABIB', region: 'korean', slugs: ['abib'] },
  { name: 'ACWELL', region: 'korean', slugs: ['acwell'] },
  { name: 'AHC', region: 'korean', slugs: ['ahc'] },
  { name: 'APLB', region: 'korean', slugs: ['aplb'] },
  { name: 'April Skin', region: 'korean', slugs: ['april-skin', 'aprilskin'] },
  { name: 'ANUA', region: 'korean', slugs: ['anua'] },
  { name: 'Arencia', region: 'korean', slugs: ['arencia'] },
  { name: 'Aromatica', region: 'korean', slugs: ['aromatica'] },
  { name: 'AXIS-Y', region: 'korean', slugs: ['axis-y', 'axisy'] },
  { name: 'Bad Skin', region: 'korean', slugs: ['bad-skin', 'badskin'] },
  { name: 'Banila Co.', region: 'korean', slugs: ['banila-co', 'banilla-co', 'banilaco'] },
  { name: 'Barulab', region: 'korean', slugs: ['barulab'] },
  { name: 'B.LAB', region: 'korean', slugs: ['b-lab', 'blab'] },
  { name: 'Beauty of Joseon', region: 'korean', slugs: ['beauty-of-joseon', 'beautyofjoseon'] },
  { name: 'Be The Skin', region: 'korean', slugs: ['be-the-skin', 'betheskin'] },
  { name: 'Belif', region: 'korean', slugs: ['belif'] },
  { name: 'Bellflower', region: 'korean', slugs: ['bellflower'] },
  { name: 'Benton', region: 'korean', slugs: ['benton'] },
  { name: 'Bonajour', region: 'korean', slugs: ['bonajour'] },
  { name: 'BRINGGREEN', region: 'korean', slugs: ['bringgreen', 'bring-green'] },
  { name: 'By Wishtrend', region: 'korean', slugs: ['by-wishtrend', 'bywishtrend'] },
  { name: 'Carenel', region: 'korean', slugs: ['carenel', 'care-nel', 'carenel-1'] },
  { name: 'Celimax', region: 'korean', slugs: ['celimax'] },
  { name: 'COMMONLABS', region: 'korean', slugs: ['commonlabs'] },
  { name: 'Cos De BAHA', region: 'korean', slugs: ['cos-de-baha', 'cosdebaha'] },
  { name: 'COSRX', region: 'korean', slugs: ['cosrx'] },
  { name: 'Coxir', region: 'korean', slugs: ['coxir'] },
  { name: 'Dear Klairs', region: 'korean', slugs: ['dear-klairs', 'klairs'] },
  { name: 'Dr. Althea', region: 'korean', slugs: ['dr-althea', 'dralthea'] },
  { name: 'Dr. Ceuracle', region: 'korean', slugs: ['dr-ceuracle', 'drceuracle'] },
  { name: 'Dr.ForHair', region: 'korean', slugs: ['dr-forhair', 'drforhair'] },
  { name: 'Dr.Jart+', region: 'korean', slugs: ['dr-jart', 'dr-jartplus', 'drjart'] },
  { name: 'Eqqualberry', region: 'korean', slugs: ['eqqualberry'] },
  { name: 'Etude House', region: 'korean', slugs: ['etude-house', 'etudehouse'] },
  { name: 'Farm Stay', region: 'korean', slugs: ['farm-stay', 'farmstay'] },
  { name: 'FINO', region: 'korean', slugs: ['fino'] },
  { name: 'FULLY', region: 'korean', slugs: ['fully'] },
  { name: 'Goodal', region: 'korean', slugs: ['goodal'] },
  { name: 'HaruHaru Wonder', region: 'korean', slugs: ['haruharu-wonder', 'haruharu', 'haruharuwonder'] },
  { name: 'Healthy Place', region: 'korean', slugs: ['healthy-place', 'healthyplace'] },
  { name: 'Heimish', region: 'korean', slugs: ['heimish'] },
  { name: 'House of Hur', region: 'korean', slugs: ['house-of-hur', 'houseofhur'] },
  { name: 'Illiyoon', region: 'korean', slugs: ['illiyoon'] },
  { name: "I'M FROM", region: 'korean', slugs: ['i-m-from', 'im-from', 'imfrom'] },
  { name: 'Innisfree', region: 'korean', slugs: ['innisfree'] },
  { name: 'Isntree', region: 'korean', slugs: ['isntree'] },
  { name: 'Iunik', region: 'korean', slugs: ['iunik'] },
  { name: 'IZEZE', region: 'korean', slugs: ['izeze'] },
  { name: 'Jumiso', region: 'korean', slugs: ['jumiso'] },
  { name: 'KAINE', region: 'korean', slugs: ['kaine'] },
  { name: 'KSECRET', region: 'korean', slugs: ['ksecret', 'k-secret'] },
  { name: 'Laneige', region: 'korean', slugs: ['laneige'] },
  { name: 'Manyo', region: 'korean', slugs: ['manyo', 'manyo-factory'] },
  { name: 'Mary & May', region: 'korean', slugs: ['mary-may', 'maryandmay', 'mary-and-may'] },
  { name: 'Medicube', region: 'korean', slugs: ['medicube'] },
  { name: 'Mise En Scene', region: 'korean', slugs: ['mise-en-scene', 'miseenscene'] },
  { name: 'Missha', region: 'korean', slugs: ['missha'] },
  { name: 'Mixsoon', region: 'korean', slugs: ['mixsoon'] },
  { name: 'Nature Republic', region: 'korean', slugs: ['nature-republic', 'naturerepublic'] },
  { name: 'Nineless', region: 'korean', slugs: ['nineless'] },
  { name: 'Numbuzin', region: 'korean', slugs: ['numbuzin'] },
  { name: 'Purito', region: 'korean', slugs: ['purito'] },
  { name: 'Pyunkang Yul', region: 'korean', slugs: ['pyunkang-yul', 'pyunkangyul'] },
  { name: 'Rated Green', region: 'korean', slugs: ['rated-green', 'ratedgreen'] },
  { name: "Rom&nd", region: 'korean', slugs: ['rom-nd', 'romand', 'rom-and'] },
  { name: 'Round Lab', region: 'korean', slugs: ['round-lab', 'roundlab'] },
  { name: 'Rovectin', region: 'korean', slugs: ['rovectin'] },
  { name: 'Ryo', region: 'korean', slugs: ['ryo'] },
  { name: 'SimplyO', region: 'korean', slugs: ['simplyo'] },
  { name: 'Skin Food', region: 'korean', slugs: ['skin-food', 'skinfood'] },
  { name: 'SKIN1004', region: 'korean', slugs: ['skin1004'] },
  { name: 'Skinmiso', region: 'korean', slugs: ['skinmiso'] },
  { name: 'Some By Mi', region: 'korean', slugs: ['some-by-mi', 'somebymi'] },
  { name: 'The Face Shop', region: 'korean', slugs: ['the-face-shop', 'thefaceshop', 'face-shop', 'the-face-sop'] },
  { name: 'Tiam', region: 'korean', slugs: ['tiam'] },
  { name: 'TIRTIR', region: 'korean', slugs: ['tirtir'] },
  { name: 'Tocobo', region: 'korean', slugs: ['tocobo'] },
  { name: 'TONYMOLY', region: 'korean', slugs: ['tonymoly', 'tony-moly'] },
  { name: 'Torriden', region: 'korean', slugs: ['torriden'] },
  { name: 'VT Cosmetics', region: 'korean', slugs: ['vt-cosmetics', 'vtcosmetics', 'vt'] },

  { name: 'Bath & Body Works', region: 'western', slugs: ['bath-body-works', 'bath-and-body-works'] },
  { name: 'Bioderma', region: 'western', slugs: ['bioderma'] },
  { name: 'CeraVe', region: 'western', slugs: ['cerave'] },
  { name: 'Cetaphil', region: 'western', slugs: ['cetaphil'] },
  { name: 'Differin', region: 'western', slugs: ['differin'] },
  { name: 'Japanese Cosmetics', region: 'western', slugs: ['japanese-cosmetics', 'japanes-cosmetics'] },
  { name: 'La Roche-Posay', region: 'western', slugs: ['la-roche-posay', 'larocheposay'] },
  { name: 'Mielle', region: 'western', slugs: ['mielle'] },
  { name: 'Neutrogena', region: 'western', slugs: ['neutrogena'] },
  { name: 'PanOxyl', region: 'western', slugs: ['panoxyl'] },
  { name: "Paula's Choice", region: 'western', slugs: ['paulas-choice', 'paula-s-choice', 'paulaschoice'] },
  { name: 'The Inkey List', region: 'western', slugs: ['the-inkey-list', 'theinkeylist', 'inkey-list'] },
  { name: 'The Ordinary', region: 'western', slugs: ['the-ordinary', 'theordinary'] },
  { name: 'Topicals', region: 'western', slugs: ['topicals'] },

  // Additional brands discovered in WC catalog (≥10 products each)
  { name: 'Dabo', region: 'korean', slugs: ['dabo'] },
  { name: 'Maybelline', region: 'western', slugs: ['maybelline', 'maybelline-new-york'] },
  { name: 'The Body Shop', region: 'western', slugs: ['the-body-shop', 'body-shop'] },
  { name: 'INSIGHT', region: 'western', slugs: ['insight'] },
  { name: 'Nivea', region: 'western', slugs: ['nivea'] },
  { name: 'RAIP', region: 'korean', slugs: ['raip'] },
  { name: 'Mamaearth', region: 'western', slugs: ['mamaearth'] },
  { name: 'SKINO', region: 'korean', slugs: ['skino'] },
  { name: 'SADOER', region: 'korean', slugs: ['sadoer'] },
  { name: 'Rohto Mentholatum', region: 'western', slugs: ['rohto-mentholatum', 'rohto', 'mentholatum'] },
  { name: 'Minimalist', region: 'western', slugs: ['minimalist'] },
  { name: 'IMAGIC Cosmetics', region: 'western', slugs: ['imagic-cosmetics', 'imagic'] },
  { name: 'Kerasys', region: 'korean', slugs: ['kerasys'] },
  { name: 'Vaseline', region: 'western', slugs: ['vaseline'] },
  { name: 'Garnier', region: 'western', slugs: ['garnier'] },
  { name: 'PHYTOTREE', region: 'korean', slugs: ['phytotree'] },
  { name: 'WishCare', region: 'western', slugs: ['wishcare'] },
  { name: "Palmer's", region: 'western', slugs: ['palmers', 'palmer-s'] },
  { name: 'BIOAQUA', region: 'western', slugs: ['bioaqua'] },
  { name: 'ORIOX', region: 'western', slugs: ['oriox'] },
  { name: 'EVERLY', region: 'western', slugs: ['everly'] },
  { name: 'Durex', region: 'western', slugs: ['durex'] },
  { name: 'PINKFLASH', region: 'western', slugs: ['pinkflash'] },
  { name: 'LMLTOP', region: 'western', slugs: ['lmltop'] },
  { name: 'Aveeno', region: 'western', slugs: ['aveeno'] },
  { name: 'TECHNIC', region: 'western', slugs: ['technic'] },
  { name: 'Holika Holika', region: 'korean', slugs: ['holika-holika', 'holikaholika'] },
  { name: 'FOODAHOLIC', region: 'korean', slugs: ['foodaholic'] },

  // Auto-imported from product catalog scan (long-tail brands).
  { name: 'Swiss', region: 'western', slugs: ['swiss'] },
  { name: 'Simple', region: 'western', slugs: ['simple'] },
  { name: 'Hada Labo', region: 'western', slugs: ['hada-labo'] },
  { name: 'Pond\'s', region: 'western', slugs: ['pond-s'] },
  { name: 'Rajkonna', region: 'western', slugs: ['rajkonna'] },
  { name: 'Neogen', region: 'western', slugs: ['neogen'] },
  { name: 'L\'Oreal', region: 'western', slugs: ['l-oreal'] },
  { name: 'Jigott', region: 'western', slugs: ['jigott'] },
  { name: 'Aqualogica', region: 'western', slugs: ['aqualogica'] },
  { name: 'PAULA’S', region: 'western', slugs: ['paula-s'] },
  { name: 'W.dressroom', region: 'western', slugs: ['w-dressroom'] },
  { name: 'freeman', region: 'western', slugs: ['freeman'] },
  { name: 'Trendy', region: 'western', slugs: ['trendy'] },
  { name: 'Laxzin', region: 'western', slugs: ['laxzin'] },
  { name: 'Daiso', region: 'western', slugs: ['daiso'] },
  { name: 'Innsaei', region: 'western', slugs: ['innsaei'] },
  { name: 'P.calm', region: 'western', slugs: ['p-calm'] },
  { name: 'Biore', region: 'western', slugs: ['biore'] },
  { name: 'W7', region: 'western', slugs: ['w7'] },
  { name: 'W.Skin Lab', region: 'western', slugs: ['w-skin-lab'] },
  { name: 'TRESemmé', region: 'western', slugs: ['tresemm'] },
  { name: 'Trendy Beauties', region: 'western', slugs: ['trendy-beauties'] },
  { name: 'Shiseido', region: 'western', slugs: ['shiseido'] },
  { name: 'Sunsilk', region: 'western', slugs: ['sunsilk'] },
  { name: 'Maange', region: 'western', slugs: ['maange'] },
  { name: 'Laikou', region: 'western', slugs: ['laikou'] },
  { name: 'Gillette', region: 'western', slugs: ['gillette'] },
  { name: 'Aestura', region: 'western', slugs: ['aestura'] },
  { name: 'Lebelage', region: 'western', slugs: ['lebelage'] },
  { name: 'Melano Cc', region: 'western', slugs: ['melano-cc'] },
  { name: 'Enchanteur', region: 'western', slugs: ['enchanteur'] },
  { name: 'Boots', region: 'western', slugs: ['boots'] },
  { name: 'Derma', region: 'western', slugs: ['derma'] },
  { name: 'A\'pieu', region: 'western', slugs: ['a-pieu'] },
  { name: 'w.skin', region: 'western', slugs: ['w-skin'] },
  { name: 'Kao', region: 'western', slugs: ['kao'] },
  { name: 'MediPeel', region: 'western', slugs: ['medipeel'] },
  { name: 'Lucido-L', region: 'western', slugs: ['lucido-l'] },
  { name: 'Superdrug', region: 'western', slugs: ['superdrug'] },
  { name: '2080', region: 'western', slugs: ['2080'] },
  { name: 'Wet', region: 'western', slugs: ['wet'] },
  { name: 'Wskin', region: 'western', slugs: ['wskin'] },
  { name: 'Vatika', region: 'western', slugs: ['vatika'] },
  { name: 'Lion', region: 'western', slugs: ['lion'] },
  { name: 'Kose Kosmeport', region: 'western', slugs: ['kose-kosmeport'] },
  { name: 'Beaute melasma X', region: 'western', slugs: ['beaute-melasma-x'] },
  { name: 'Neko', region: 'western', slugs: ['neko'] },
  { name: 'Seba Med', region: 'western', slugs: ['seba-med'] },
  { name: 'Veet', region: 'western', slugs: ['veet'] },
  { name: 'Nair', region: 'western', slugs: ['nair'] },
  { name: 'Eucerin', region: 'western', slugs: ['eucerin'] },
  { name: 'Dr.', region: 'western', slugs: ['dr'] },
  { name: 'Yanagiya', region: 'western', slugs: ['yanagiya'] },
  { name: 'Yadah', region: 'western', slugs: ['yadah'] },
  { name: 'XiSJOEM', region: 'western', slugs: ['xisjoem'] },
  { name: 'Vanicream', region: 'western', slugs: ['vanicream'] },
  { name: 'Valencia', region: 'western', slugs: ['valencia'] },
  { name: 'Sudocrem', region: 'western', slugs: ['sudocrem'] },
  { name: 'T-park', region: 'western', slugs: ['t-park'] },
  { name: 'Sweet', region: 'western', slugs: ['sweet'] },
  { name: 'Skin\'o', region: 'western', slugs: ['skin-o'] },
  { name: 'Skinlogic', region: 'western', slugs: ['skinlogic'] },
  { name: 'Sebamed', region: 'western', slugs: ['sebamed'] },
  { name: 'Cezanne', region: 'western', slugs: ['cezanne'] },
  { name: 'Rivaj', region: 'western', slugs: ['rivaj'] },
  { name: 'Revolution', region: 'western', slugs: ['revolution'] },
  { name: 'Remington', region: 'western', slugs: ['remington'] },
  { name: 'Paxmoly', region: 'western', slugs: ['paxmoly'] },
  { name: 'Panam', region: 'western', slugs: ['panam'] },
  { name: 'Concealar', region: 'western', slugs: ['concealar'] },
  { name: 'Sponges', region: 'western', slugs: ['sponges'] },
  { name: 'Multifunction', region: 'western', slugs: ['multifunction'] },
  { name: 'Muuchstac', region: 'western', slugs: ['muuchstac'] },
  { name: 'Miyako', region: 'western', slugs: ['miyako'] },
  { name: 'Mistine', region: 'western', slugs: ['mistine'] },
  { name: 'Magefy', region: 'western', slugs: ['magefy'] },
  { name: 'Luofmiss', region: 'western', slugs: ['luofmiss'] },
  { name: 'Lanbena', region: 'western', slugs: ['lanbena'] },
  { name: 'Karite', region: 'western', slugs: ['karite'] },
  { name: 'J.cat', region: 'western', slugs: ['j-cat'] },
  { name: 'Hawaa', region: 'western', slugs: ['hawaa'] },
  { name: 'Dove', region: 'western', slugs: ['dove'] },
  { name: 'Moist', region: 'western', slugs: ['moist'] },
  { name: 'Skinlife', region: 'western', slugs: ['skinlife'] },
  { name: 'Radiant', region: 'western', slugs: ['radiant'] },
  { name: 'Clear', region: 'western', slugs: ['clear'] },
  { name: 'Femi-fresh', region: 'western', slugs: ['femi-fresh'] },
  { name: 'Novale', region: 'western', slugs: ['novale'] },
  { name: 'Japanese', region: 'western', slugs: ['japanese'] },
  { name: 'Aztec', region: 'western', slugs: ['aztec'] },
  { name: 'Absolute', region: 'western', slugs: ['absolute'] },
  { name: 'AMPLE:N', region: 'western', slugs: ['ample-n'] },
  { name: 'Tretinoin', region: 'western', slugs: ['tretinoin'] },
  { name: 'Valentine', region: 'western', slugs: ['valentine'] },
  { name: 'Needly', region: 'western', slugs: ['needly'] },
  { name: 'Apieu', region: 'western', slugs: ['apieu'] },
  { name: 'Instree', region: 'western', slugs: ['instree'] },
  { name: 'Athena', region: 'western', slugs: ['athena'] },
  { name: 'Cellpod', region: 'western', slugs: ['cellpod'] },
  { name: 'Nizoral', region: 'western', slugs: ['nizoral'] },
  { name: 'Seapuri', region: 'western', slugs: ['seapuri'] },
  { name: 'Naturie', region: 'western', slugs: ['naturie'] },
  { name: 'Reihaku', region: 'western', slugs: ['reihaku'] },
  { name: 'Seoul', region: 'western', slugs: ['seoul'] },
  { name: 'Purcell', region: 'western', slugs: ['purcell'] },
  { name: 'Be-hope', region: 'western', slugs: ['be-hope'] },
  { name: 'Ruthair', region: 'western', slugs: ['ruthair'] },
  { name: 'Ongredients', region: 'western', slugs: ['ongredients'] },
  { name: 'Kopher', region: 'western', slugs: ['kopher'] },
  { name: 'Atomy', region: 'western', slugs: ['atomy'] },
  { name: 'Beaute Melasma', region: 'western', slugs: ['beaute-melasma'] },
  { name: 'Ottogi', region: 'western', slugs: ['ottogi'] },
  { name: 'Fiorese', region: 'western', slugs: ['fiorese'] },
  { name: 'Syoss', region: 'western', slugs: ['syoss'] },
  { name: 'Byphasse', region: 'western', slugs: ['byphasse'] },
  { name: 'Luzin', region: 'western', slugs: ['luzin'] },
  { name: 'Beyond', region: 'western', slugs: ['beyond'] },
  { name: 'Median', region: 'western', slugs: ['median'] },
  { name: 'Gamdong', region: 'western', slugs: ['gamdong'] },
  { name: 'Sulwhasoo', region: 'western', slugs: ['sulwhasoo'] },
  { name: 'Basic', region: 'western', slugs: ['basic'] },
  { name: 'Medi-peel', region: 'western', slugs: ['medi-peel'] },
  { name: 'Korea', region: 'western', slugs: ['korea', 'korean'] },
  { name: 'Guerisson', region: 'western', slugs: ['guerisson'] },
  { name: 'Labelyoung', region: 'western', slugs: ['labelyoung'] },
  { name: 'Samyang', region: 'western', slugs: ['samyang'] },
  { name: 'Glass', region: 'western', slugs: ['glass'] },
  { name: 'Hyperpigmentation', region: 'western', slugs: ['hyperpigmentation'] },
  { name: 'Sensitive', region: 'western', slugs: ['sensitive'] },
  { name: 'Anti-acne', region: 'western', slugs: ['anti-acne'] },
  { name: 'Melasma', region: 'western', slugs: ['melasma'] },
  { name: 'Cloud', region: 'western', slugs: ['cloud'] },
  { name: 'Yuhan', region: 'western', slugs: ['yuhan'] },
  { name: 'Holidays', region: 'western', slugs: ['holidays'] },
  { name: 'South', region: 'western', slugs: ['south'] },
  { name: 'Grincelllabs', region: 'western', slugs: ['grincelllabs'] },
  { name: 'Young', region: 'western', slugs: ['young'] },
  { name: 'Plu365', region: 'western', slugs: ['plu365'] },
  { name: 'Welcos', region: 'western', slugs: ['welcos'] },
  { name: 'Lucido', region: 'western', slugs: ['lucido'] },
  { name: 'Embla', region: 'western', slugs: ['embla'] },
  { name: 'Krave', region: 'western', slugs: ['krave'] },
  { name: 'beaute moringa melasma', region: 'western', slugs: ['beaute-moringa-melasma'] },
  { name: 'beaute melasma X Collagen', region: 'western', slugs: ['beaute-melasma-x-collagen'] },
  { name: 'beaute melasma X AHA BHA', region: 'western', slugs: ['beaute-melasma-x-aha-bha'] },
  { name: 'beaute melasma X Hyluronic', region: 'western', slugs: ['beaute-melasma-x-hyluronic'] },
  { name: 'beaute melasma 3d whitening', region: 'western', slugs: ['beaute-melasma-3d-whitening'] },
  { name: 'Aloe vera', region: 'western', slugs: ['aloe-vera'] },
  { name: 'Cold Pressed', region: 'western', slugs: ['cold-pressed'] },
  { name: 'Sabamed', region: 'western', slugs: ['sabamed'] },
  { name: 'Beauty Glazed', region: 'western', slugs: ['beauty-glazed'] },
  { name: 'Green Finger', region: 'korean', slugs: ['green-finger'] },
  { name: 'Sungboon Editor', region: 'korean', slugs: ['sungboon-editor'] },
  { name: 'ZEZE', region: 'korean', slugs: ['zeze'] },
  { name: 'Korea Red Ginseng', region: 'korean', slugs: ['korea-red-ginseng'] },
  { name: 'Kojie San', region: 'western', slugs: ['kojie-san'] },
  { name: 'essence', region: 'western', slugs: ['essence'] },
  { name: 'Beauty Formulas', region: 'western', slugs: ['beauty-formulas'] },
];

const slugToCanonical = new Map<string, CanonicalBrand>();
for (const brand of CANONICAL_BRANDS) {
  for (const slug of brand.slugs) {
    slugToCanonical.set(slug.toLowerCase(), brand);
  }
}

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/gi, '&')
    .replace(/&#039;/g, "'")
    .replace(/&apos;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/&nbsp;/gi, ' ');
}

function normalizeSlug(input: string): string {
  return decodeEntities(input)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function findCanonicalBrand(slugOrName: string): CanonicalBrand | undefined {
  if (!slugOrName) return undefined;
  const direct = slugToCanonical.get(slugOrName.toLowerCase());
  if (direct) return direct;
  return slugToCanonical.get(normalizeSlug(slugOrName));
}

export function isWhitelistedBrandSlug(slug: string): boolean {
  return slugToCanonical.has(slug.toLowerCase());
}
