export interface OriginDefinition {
  country: string;
  aliases?: string[];
  code: string;
  label: string;
  flag: string;
  region: string;
  hue: number;
  desc: string;
  story: string;
}

export const ORIGIN_DEFINITIONS: OriginDefinition[] = [
  {
    country: 'south-korea',
    aliases: ['korea'],
    code: 'KR',
    label: 'South Korea',
    flag: '🇰🇷',
    region: 'East Asia',
    hue: 320,
    desc: 'Korean skincare and beauty brands.',
    story: 'Barrier care, hydrating toners, calming serums, lightweight creams, and daily sunscreen innovation.',
  },
  {
    country: 'japan',
    code: 'JP',
    label: 'Japan',
    flag: '🇯🇵',
    region: 'East Asia',
    hue: 354,
    desc: 'Japanese skincare, sunscreen, and beauty picks.',
    story: 'Minimal routines, elegant sunscreens, cleansing oils, lotions, and gentle daily skin maintenance.',
  },
  {
    country: 'china',
    code: 'CN',
    label: 'China',
    flag: '🇨🇳',
    region: 'East Asia',
    hue: 18,
    desc: 'Chinese beauty and personal care brands.',
    story: 'Fast-moving beauty finds, makeup staples, personal care, and accessible skincare essentials.',
  },
  {
    country: 'taiwan',
    code: 'TW',
    label: 'Taiwan',
    flag: '🇹🇼',
    region: 'East Asia',
    hue: 210,
    desc: 'Taiwanese skincare and beauty finds.',
    story: 'Sheet masks, gentle hydration, practical skincare, and sensitive-skin friendly daily care.',
  },
  {
    country: 'usa',
    code: 'US',
    label: 'USA',
    flag: '🇺🇸',
    region: 'North America',
    hue: 245,
    desc: 'American skincare, body care, and makeup brands.',
    story: 'Dermatologist-led skincare, acne care, body care, makeup, and practical everyday routines.',
  },
  {
    country: 'uk',
    code: 'GB',
    label: 'UK',
    flag: '🇬🇧',
    region: 'Europe',
    hue: 268,
    desc: 'British skincare, haircare, and makeup brands.',
    story: 'Accessible skincare, body care, haircare, pharmacy favorites, and trend-driven makeup.',
  },
  {
    country: 'france',
    code: 'FR',
    label: 'France',
    flag: '🇫🇷',
    region: 'Europe',
    hue: 220,
    desc: 'French pharmacy and luxury skincare brands.',
    story: 'Pharmacy skincare, thermal water, barrier repair, sunscreen, and sensitive-skin derma care.',
  },
  {
    country: 'germany',
    code: 'DE',
    label: 'Germany',
    flag: '🇩🇪',
    region: 'Europe',
    hue: 42,
    desc: 'German derma and personal care brands.',
    story: 'Body care, derma staples, family skincare, and practical formulas for repeated daily use.',
  },
  {
    country: 'canada',
    code: 'CA',
    label: 'Canada',
    flag: '🇨🇦',
    region: 'North America',
    hue: 4,
    desc: 'Canadian skincare and beauty brands.',
    story: 'Gentle skincare, cold-weather hydration, fragrance, body care, and practical beauty staples.',
  },
  {
    country: 'poland',
    code: 'PL',
    label: 'Poland',
    flag: '🇵🇱',
    region: 'Europe',
    hue: 350,
    desc: 'Polish skincare and beauty brands.',
    story: 'Affordable European skincare, cleansing, haircare, and everyday personal care products.',
  },
  {
    country: 'spain',
    code: 'ES',
    label: 'Spain',
    flag: '🇪🇸',
    region: 'Europe',
    hue: 38,
    desc: 'Spanish skincare and beauty brands.',
    story: 'Sun-aware skincare, pharmacy care, fragrance, makeup, and Mediterranean beauty essentials.',
  },
  {
    country: 'india',
    code: 'IN',
    label: 'India',
    flag: '🇮🇳',
    region: 'South Asia',
    hue: 28,
    desc: 'Indian skincare, haircare, and makeup brands.',
    story: 'Haircare, sunscreen, actives, makeup, herbal care, and humid-weather routines familiar to South Asia.',
  },
  {
    country: 'thailand',
    code: 'TH',
    label: 'Thailand',
    flag: '🇹🇭',
    region: 'Southeast Asia',
    hue: 8,
    desc: 'Thai beauty and personal care finds.',
    story: 'Lightweight textures, sun care, body care, brightening routines, and tropical-climate beauty.',
  },
  {
    country: 'bangladesh',
    code: 'BD',
    label: 'Bangladesh',
    flag: '🇧🇩',
    region: 'South Asia',
    hue: 165,
    desc: 'Bangladeshi beauty and personal care brands.',
    story: 'Local and regional beauty essentials selected for Bangladesh shoppers and everyday climate needs.',
  },
  {
    country: 'malaysia',
    code: 'MY',
    label: 'Malaysia',
    flag: '🇲🇾',
    region: 'Southeast Asia',
    hue: 230,
    desc: 'Malaysian beauty and personal care brands.',
    story: 'Halal-friendly beauty, tropical-climate skincare, personal care, and everyday routine staples.',
  },
  {
    country: 'philippines',
    code: 'PH',
    label: 'Philippines',
    flag: '🇵🇭',
    region: 'Southeast Asia',
    hue: 52,
    desc: 'Philippine beauty and personal care brands.',
    story: 'Humidity-ready beauty, body care, sunscreen, and accessible personal care favorites.',
  },
  {
    country: 'sri-lanka',
    code: 'LK',
    label: 'Sri Lanka',
    flag: '🇱🇰',
    region: 'South Asia',
    hue: 70,
    desc: 'Sri Lankan beauty and personal care brands.',
    story: 'Herbal care, haircare, body care, and regional beauty essentials with South Asian familiarity.',
  },
  {
    country: 'pakistan',
    code: 'PK',
    label: 'Pakistan',
    flag: '🇵🇰',
    region: 'South Asia',
    hue: 140,
    desc: 'Pakistani beauty and personal care brands.',
    story: 'Regional beauty, haircare, makeup, and personal care products for familiar climate needs.',
  },
  {
    country: 'uae',
    code: 'AE',
    label: 'UAE',
    flag: '🇦🇪',
    region: 'Middle East',
    hue: 145,
    desc: 'UAE beauty and personal care brands.',
    story: 'Fragrance, body care, personal care, and beauty products shaped by warm-weather routines.',
  },
  {
    country: 'south-africa',
    code: 'ZA',
    label: 'South Africa',
    flag: '🇿🇦',
    region: 'Africa',
    hue: 120,
    desc: 'South African beauty and personal care brands.',
    story: 'Body care, haircare, sun care, and practical beauty products for everyday routines.',
  },
  {
    country: 'turkey',
    code: 'TR',
    label: 'Turkey',
    flag: '🇹🇷',
    region: 'Middle East',
    hue: 358,
    desc: 'Turkish beauty and personal care brands.',
    story: 'Cleansing, body care, fragrance, bath traditions, and accessible personal care products.',
  },
  {
    country: 'multinational',
    code: 'GL',
    label: 'Multinational',
    flag: '🌍',
    region: 'Global',
    hue: 185,
    desc: 'Brands with multinational origin or ownership.',
    story: 'Global beauty groups and brands where ownership, manufacturing, or heritage spans multiple countries.',
  },
];

export function getOriginByCountry(country?: string) {
  if (!country) return undefined;
  const normalized = country.toLowerCase().trim();
  return ORIGIN_DEFINITIONS.find((origin) => (
    origin.country === normalized || origin.aliases?.includes(normalized)
  ));
}
